### ISSUE TITLE
Error in Import

### ISSUE THREAD

**Issue by Muneer111** [gregcaporaso/q2-sapienns#13]
Dear Professor
I trust you are fine and doing good
I am trying to use q2-sapienns plugin in qiime2, by following the instructions, I have successfully installed the plugin.
I then tried to run the command  **qiime tools import --input-path Galaxy.tsv --output-path Galaxy_outPut.qza --type MetaphlanAbundanceTable** and got the error 
Traceback (most recent call last):
  File "/home/qiime2/miniconda/envs/qiime2-2021.11/lib/python3.8/site-packages/q2cli/builtin/tools.py", line 157, in import_data
    artifact = qiime2.sdk.Artifact.import_data(type, input_path,
  File "/home/qiime2/miniconda/envs/qiime2-2021.11/lib/python3.8/site-packages/qiime2/sdk/result.py", line 250, in import_data
    output_dir_fmt = pm.get_directory_format(type_)
  File "/home/qiime2/miniconda/envs/qiime2-2021.11/lib/python3.8/site-packages/qiime2/sdk/plugin_manager.py", line 354, in get_directory_format
    raise TypeError(
TypeError: Semantic type MetaphlanAbundanceTable does not have a compatible directory format.

An unexpected error has occurred:

  Semantic type MetaphlanAbundanceTable does not have a compatible directory format.

See above for debug info.
**I am also attaching the file** , the analysis was carried out in Galaxy using Metaphlan

![image](https://github.com/gregcaporaso/q2-sapienns/assets/76723877/79f5ae62-c2ae-4956-9ade-51cdb138db88)
Kindly, suggest
Thanks and Regards

**Comment by Muneer111** [comment]
Dear Professor 
Gentle reminder
Thanks and Regards

**Comment by gregcaporaso** [comment]
Hi @Muneer111, Sorry for missing this. Are you still stuck on this issue? If so, do you mind posting to the [QIIME 2 Forum](https://forum.qiime2.org) with a description of how you installed q2-sapienns? 

Also, you may have better luck now installing the [QIIME 2 shotgun distribution](https://docs.qiime2.org/2023.9/install/native/#qiime-2-shotgun-distribution), which includes q2-sapienns.
